site_name: gd.py
site_author: nekitdev
site_description: An API wrapper for Geometry Dash written in Python.

repo_name: nekitdev/gd.py
repo_url: https://github.com/nekitdev/gd.py

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Reference:
    - Client: "reference/client.md"
    - Encoding: "reference/encoding.md"
    - Enums: "reference/enums.md"
    - Songs: "reference/songs.md"
    - Artist: "reference/artist.md"
    - Tasks: "reference/tasks.md"
    - API:
      - Editor: "reference/api/editor.md"
      - Color Channels: "reference/api/color_channels.md"
      - Guidelines: "reference/api/guidelines.md"
      - Folder: "reference/api/folder.md"
    - Memory:
      - Internal: "reference/memory/internal.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - gd

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: deep orange
      accent: light blue

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [gd]

          import:
            - https://docs.python.org/3/objects.inv
            - https://nekitdev.github.io/versions/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
