APPLICATION_JSON = "application/json"

AUTHORIZATION = "Authorization"

CLIENT = "client"

TOKEN = "token"
TOKENS = "tokens"

TITLE = "API Documentation"

DOCS = "/api/docs"
INFO = "/api/docs/info.json"

GD = ".gd"

PREFIX = "/api"
VERSION = 1
VERSION_FORMAT = "v{}"

QUERY = "query"

HTTP_OK = 200
HTTP_CREATED = 201

HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_TOO_MANY_REQUESTS = 429

HTTP_INTERNAL_SERVER_ERROR = 500

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8080
