DEFAULT_ALIGNMENT = 0
DEFAULT_SIZE = 0

DEFAULT_PACKED = False
DEFAULT_VIRTUAL = False

DEFAULT_BASE = 0

DEFAULT_OFFSET = 0
DEFAULT_EXCLUDE = False

ZERO_SIZE = 0

CONTENT_LENGTH = 16

WINDOWS_GAME_MANAGER_OFFSET = 0x3222D0
WINDOWS_ACCOUNT_MANAGER_OFFSET = 0x3222D8

DARWIN_GAME_MANAGER_OFFSET = 0x69E398
DARWIN_ACCOUNT_MANAGER_OFFSET = 0x69C698
