class Route:
    GET_USER_INFO = 'getGJUserInfo20'
    USER_SEARCH = 'getGJUsers20'
    DOWNLOAD_LEVEL = 'downloadGJLevel22'
    LEVEL_SEARCH = 'getGJLevels21'
    GET_SONG_INFO = 'getGJSongInfo'
    GET_FRIENDS = 'getGJUserList20'
    GET_COMMENTS = 'getGJAccountComments20'
    GET_PRIVATE_MESSAGES = 'getGJMessages20'
    READ_PRIVATE_MESSAGE = 'downloadGJMessage20'
    SEND_PRIVATE_MESSAGE = 'uploadGJMessage20'
    DELETE_PRIVATE_MESSAGE = 'deleteGJMessages20'
    GET_TIMELY = 'getGJDailyLevel'
    LOGIN = 'accounts/loginGJAccount'
    DELETE_ACC_COMMENT = 'deleteGJAccComment20'
    DELETE_LEVEL_COMMENT = 'deleteGJComment20'
    UPLOAD_COMMENT = 'uploadGJComment21'
    UPLOAD_ACC_COMMENT = 'uploadGJAccComment20'
    REQUEST_MODERATOR = 'requestUserAccess'
    #LIKE_LEVELS and stuff go here