EMPTY = str()
SPACE = " "

UNKNOWN = "unknown"
UNNAMED = "unnamed"

DEFAULT_COLOR_1_ID = 0
DEFAULT_COLOR_2_ID = 3

DEFAULT_GLOW = False

DEFAULT_ID = 0

DEFAULT_SIZE = 0.0

DEFAULT_RECORD = 0

DEFAULT_SPECIAL = 0

DEFAULT_COUNT = 100

ZERO_PAGE = range(1)

COMMENT_PAGE_SIZE = 20

DEFAULT_LOAD_AFTER_POST = True

DEFAULT_GET_DATA = True
DEFAULT_USE_CLIENT = False

DEFAULT_SERVER_STYLE = True
DEFAULT_RETURN_DEFAULT = True

DEFAULT_FROM_NEWGROUNDS = False

DEFAULT_WITH_BAR = False

DEFAULT_PAGE = 0

DEFAULT_PAGES_COUNT = 10
DEFAULT_PAGES = range(DEFAULT_PAGES_COUNT)

DEFAULT_WIDTH = 250
DEFAULT_HEIGHT = 250

DEFAULT_ENCODING = "utf-8"
DEFAULT_ERRORS = "strict"

BYTE = 0xFF
BITS = BYTE.bit_length()
DOUBLE_BITS = BITS + BITS
