from gd.constants import SPACE

ARTIST_SEPARATOR = ":"

SONG_SEPARATOR = "~|~"

LOGIN_SEPARATOR = ","

CREATOR_SEPARATOR = ":"
SEARCH_USER_SEPARATOR = ":"
PROFILE_SEPARATOR = ":"
RELATIONSHIP_USER_SEPARATOR = ":"
LEADERBOARD_USER_SEPARATOR = ":"

TIMELY_INFO_SEPARATOR = "|"

MESSAGE_SEPARATOR = ":"

FRIEND_REQUEST_SEPARATOR = ":"

LEVEL_SEPARATOR = ":"

LEVEL_COMMENT_INNER_SEPARATOR = "~"
LEVEL_COMMENT_USER_SEPARATOR = "~"
LEVEL_LEADERBOARD_USER_SEPARATOR = ":"
LEVEL_COMMENT_SEPARATOR = ":"
USER_COMMENT_SEPARATOR = "~"

GAUNTLET_SEPARATOR = ":"
MAP_PACK_SEPARATOR = ":"

QUEST_SEPARATOR = ","
CHEST_SEPARATOR = ","

QUESTS_INNER_SEPARATOR = ":"
CHESTS_INNER_SEPARATOR = ":"

LEVEL_IDS_SEPARATOR = ","

NAME_SEPARATOR = "_"

PAGE_SEPARATOR = ":"

LIKE_SEPARATOR = "_"

COMMENT_BANNED_SEPARATOR = "_"

HSV_SEPARATOR = "a"

PROGRESS_SEPARATOR = ","

COLOR_SEPARATOR = ","

SAVE_SEPARATOR = ";"

HEADER_SEPARATOR = ","

COLOR_CHANNEL_SEPARATOR = "_"
COLOR_CHANNELS_SEPARATOR = "|"

OBJECT_SEPARATOR = ","
GROUPS_SEPARATOR = "."
OBJECTS_SEPARATOR = ";"

GUIDELINES_SEPARATOR = "~"

TIME_SEPARATOR = ","
TIME_SEPARATOR_SPACE = TIME_SEPARATOR + SPACE

RECORDING_ITEM_SEPARATOR = ";"

ARTISTS_RESPONSE_SEPARATOR = "#"
ARTISTS_RESPONSE_ARTISTS_SEPARATOR = "|"

SEARCH_USERS_RESPONSE_SEPARATOR = "#"
SEARCH_USERS_RESPONSE_USERS_SEPARATOR = "|"

RELATIONSHIPS_RESPONSE_USERS_SEPARATOR = "|"

LEADERBOARD_RESPONSE_USERS_SEPARATOR = "|"

MESSAGES_RESPONSE_SEPARATOR = "#"
MESSAGES_RESPONSE_MESSAGES_SEPARATOR = "|"

FRIEND_REQUESTS_RESPONSE_SEPARATOR = "#"
FRIEND_REQUESTS_RESPONSE_FRIEND_REQUESTS_SEPARATOR = "|"

LEVEL_RESPONSE_SEPARATOR = "#"

SEARCH_LEVELS_RESPONSE_SEPARATOR = "#"
SEARCH_LEVELS_RESPONSE_LEVELS_SEPARATOR = "|"
SEARCH_LEVELS_RESPONSE_CREATORS_SEPARATOR = "|"
SEARCH_LEVELS_RESPONSE_SONGS_SEPARATOR = "~:~"

USER_COMMENTS_RESPONSE_SEPARATOR = "#"
USER_COMMENTS_RESPONSE_COMMENTS_SEPARATOR = "|"

LEVEL_COMMENTS_RESPONSE_SEPARATOR = "#"
LEVEL_COMMENTS_RESPONSE_COMMENTS_SEPARATOR = "|"

LEVEL_LEADERBOARD_RESPONSE_USERS_SEPARATOR = "|"

QUESTS_RESPONSE_SEPARATOR = "|"
CHESTS_RESPONSE_SEPARATOR = "|"

GAUNTLETS_RESPONSE_SEPARATOR = "#"
GAUNTLETS_RESPONSE_GAUNTLETS_SEPARATOR = "|"

MAP_PACKS_RESPONSE_SEPARATOR = "#"
MAP_PACKS_RESPONSE_MAP_PACKS_SEPARATOR = "|"

CAPACITY_SEPARATOR = "_"
