from gd.constants import SPACE

ONE = str(1)

SONG_SEPARATOR = "~|~"
LOGIN_SEPARATOR = ","
CREATOR_SEPARATOR = ":"
SEARCH_USER_SEPARATOR = ":"
PROFILE_SEPARATOR = ":"
PAGE_SEPARATOR = ":"
COMMENT_BANNED_SEPARATOR = "_"
EXTRA_STRING_SEPARATOR = "_"
HSV_SEPARATOR = "a"
COLOR_SEPARATOR = ","
DATABASE_SEPARATOR = ";"
HEADER_SEPARATOR = ","
OBJECTS_SEPARATOR = ";"
TIME_SEPARATOR = ","
TIME_SEPARATOR_SPACE = TIME_SEPARATOR + SPACE
RECORDING_SEPARATOR = ";"
SEARCH_USERS_RESPONSE_SEPARATOR = "#"
SEARCH_USERS_RESPONSE_USERS_SEPARATOR = "|"
