name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update submodules
        run: git submodule update --init --remote

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org/ | python -

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --with docs --all-extras

      - name: Pull
        run: git pull

      - name: Deploy the documentation
        run: poetry run mkdocs gh-deploy
